version: '3.8'

services:
  app:
    image: device-service:latest # This must match the name of the image you built for your app
    container_name: device-service
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - gbl_network
  mysql:
    image: mysql:8.0
    container_name: device
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: device
      MYSQL_USER: user
      MYSQL_PASSWORD: myPassword
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gbl_network
    restart: always

volumes:
  db_data:

networks:
  gbl_network:
    driver: bridge
