version: '3.8'

services:
  app:
    image: device-service:latest # This must match the name of the image you built for your app
    container_name: device-service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - gbl_network
    environment:
      - WAIT_HOSTS=mysql:3306
  mysql:
    image: mysql:8.0
    container_name: device
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: device
      MYSQL_USER: user
      MYSQL_PASSWORD: myPassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gbl_network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 5s
      interval: 5s
      timeout: 20s
      retries: 10
volumes:
  db_data:

networks:
  gbl_network:
    driver: bridge
